#!/usr/bin/env ruby

if ARGV.size.zero?
  # Open irb
  text = <<~TEXT
  nPython 0.16.0 (main, Nov 16 2025, 18:38:03) [GCC] on linux
  Type "help", "copyright", "credits" or "license" for more information.
  TEXT
  puts text

  system("irb --prompt simple --nocolorize --noecho-on-assignment -Ilib -rnpython")
else
  require_relative "lib/nython"
  content = File.read(ARGV.first)
  eval(content)
end
